DROP SEQUENCE orderSeq;
DROP TABLE ORDERPAGE;

CREATE SEQUENCE orderSeq;

CREATE TABLE ORDERPAGE (
	PROJECTNAME VARCHAR2(1000),
	TOTALPRICE NUMBER,
	USERNAME VARCHAR2(100),
	ADDRESS VARCHAR2(100),
	PHONE NUMBER
	
);

INSERT INTO ORDERPAGE
VALUES('사과', 20000, '김대진', '대진이네', 12345);


SELECT * FROM ORDERPAGE;
